import { Head, useForm } from '@inertiajs/react';
import { ArrowUpRight, CheckCircle2, Send } from 'lucide-react';
import SiteLayout from '../components/SiteLayout';
import { profile } from '../data/portfolio';

export default function Contact({ success }) {
    const { data, setData, post, processing, errors, reset } = useForm({ name: '', email: '', company: '', service: '', message: '', consent: false, website: '' });
    const submit = (event) => { event.preventDefault(); post('/contact', { preserveScroll: true, onSuccess: () => reset() }); };
    return <SiteLayout><Head title="Contact" /><section className="contact-page section-pad"><div className="contact-intro"><p className="eyebrow"><span />Let’s work together</p><h1>Tell me what you’re building—or what needs fixing.</h1><p>Share a little about your website, application, QA need, or search challenge. I’ll review your message and reply by email.</p><div className="direct-links"><a href={`mailto:${profile.email}`}>{profile.email}<ArrowUpRight /></a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn<ArrowUpRight /></a><span>{profile.location}</span></div></div><div className="contact-panel">{success && <div className="success-message" role="status"><CheckCircle2 />{success}</div>}<form onSubmit={submit} noValidate><div className="field-grid"><label>Full name<input value={data.name} onChange={(e) => setData('name', e.target.value)} autoComplete="name" />{errors.name && <span>{errors.name}</span>}</label><label>Email address<input type="email" value={data.email} onChange={(e) => setData('email', e.target.value)} autoComplete="email" />{errors.email && <span>{errors.email}</span>}</label></div><div className="field-grid"><label>Company <small>Optional</small><input value={data.company} onChange={(e) => setData('company', e.target.value)} autoComplete="organization" /></label><label>What can I help with?<select value={data.service} onChange={(e) => setData('service', e.target.value)}><option value="">Choose a service</option><option>Website development</option><option>Website or mobile QA</option><option>Test automation</option><option>UI/UX review</option><option>SEO and website improvement</option><option>Technical support</option><option>Something else</option></select>{errors.service && <span>{errors.service}</span>}</label></div><label>Project details<textarea rows="6" value={data.message} onChange={(e) => setData('message', e.target.value)} placeholder="What are you working on, and what would a good result look like?" />{errors.message && <span>{errors.message}</span>}</label><label className="honeypot" aria-hidden="true">Website<input tabIndex="-1" autoComplete="off" value={data.website} onChange={(e) => setData('website', e.target.value)} /></label><label className="consent"><input type="checkbox" checked={data.consent} onChange={(e) => setData('consent', e.target.checked)} /><span>I agree that my details can be used to reply to this inquiry.</span></label>{errors.consent && <span className="form-error">{errors.consent}</span>}<button className="button button--primary" type="submit" disabled={processing}>{processing ? 'Sending…' : 'Send inquiry'}<Send size={17} /></button><p className="privacy-note">Your message is used only to respond to your inquiry. No account will be created.</p></form></div></section></SiteLayout>;
}
